version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/gestion_pacientes/gestion_pacientes"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
