name: Pipeline CI/CD - Gestión de Pacientes

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Compilar y Publicar en GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Java JDK 21 # <-- Actualizado para calzar con tu pom.xml
        uses: actions/setup-java@v4
        with:
          java-version: '21'        # <-- Cambiado a Java 21
          distribution: 'temurin'
          cache: maven

      - name: Compilar y empaquetar con Maven
        working-directory: gestion_pacientes
        run: |
          ./mvnw clean package -DskipTests

      # Nota: Aquí puedes sumar los pasos de SonarCloud y Docker Hub solicitados por la rúbrica
