name: Pipeline de SaludPlus

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package -DskipTests

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/maven@master
      # Se eliminó "continue-on-error: true" para cumplir con el IE6 (romper el pipeline ante fallas)
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Build Docker Image
      run: |
        docker build -t gestion-pacientes:latest -f gestion_pacientes/gestion_pacientes/Dockerfile .